all: nid_management

CC = gcc

CFLAGS = -g -Wall -ansi

INCLUDE = /home/sccsatmtn/GradProject/include

nid_management: nid_management.c
	$(CC) nid_management.c -I$(INCLUDE) $(CFLAGS) -o nid_management
